//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:36:04 PM IST 
//


package com.macys.loyalty.schemas.loyalty_account.ltyaccountrequest.v12_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.AddressDetails;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.DOBDetails;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.NameDetails;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}NameDetails"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}AddressDetails" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}Phone" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}Email" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}DOBDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameDetails",
    "addressDetails",
    "phone",
    "email",
    "dobDetails"
})
@XmlRootElement(name = "CustomerInfo")
public class CustomerInfo {

    @XmlElement(name = "NameDetails", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected NameDetails nameDetails;
    @XmlElement(name = "AddressDetails", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected AddressDetails addressDetails;
    @XmlElement(name = "Phone", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected String phone;
    @XmlElement(name = "Email", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected String email;
    @XmlElement(name = "DOBDetails", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected DOBDetails dobDetails;

    /**
     * NameDetails: The name of Loyalty Customer
     * 
     * @return
     *     possible object is
     *     {@link NameDetails }
     *     
     */
    public NameDetails getNameDetails() {
        return nameDetails;
    }

    /**
     * Sets the value of the nameDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameDetails }
     *     
     */
    public void setNameDetails(NameDetails value) {
        this.nameDetails = value;
    }

    /**
     * AddressDetails: Postal Address of Loyalty Customer
     * 
     * @return
     *     possible object is
     *     {@link AddressDetails }
     *     
     */
    public AddressDetails getAddressDetails() {
        return addressDetails;
    }

    /**
     * Sets the value of the addressDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDetails }
     *     
     */
    public void setAddressDetails(AddressDetails value) {
        this.addressDetails = value;
    }

    /**
     * Phone: Phone number of the Loyalty Customer. This phone number is also used for Lookup of the customer.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Email: Email address of the Loyalty Customer
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * DOBDetails: Date of Birth of Loyalty Customer
     * 
     * @return
     *     possible object is
     *     {@link DOBDetails }
     *     
     */
    public DOBDetails getDOBDetails() {
        return dobDetails;
    }

    /**
     * Sets the value of the dobDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOBDetails }
     *     
     */
    public void setDOBDetails(DOBDetails value) {
        this.dobDetails = value;
    }

}
