//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AwardSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AwardSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="YTDAwardCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="YTDAwardValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="LifeTimeAwardCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LifeTimeAwardValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AwardSummary", propOrder = {
    "ytdAwardCount",
    "ytdAwardValue",
    "lifeTimeAwardCount",
    "lifeTimeAwardValue"
})
public class AwardSummary {

    @XmlElement(name = "YTDAwardCount")
    protected int ytdAwardCount;
    @XmlElement(name = "YTDAwardValue", required = true)
    protected BigDecimal ytdAwardValue;
    @XmlElement(name = "LifeTimeAwardCount")
    protected int lifeTimeAwardCount;
    @XmlElement(name = "LifeTimeAwardValue", required = true)
    protected BigDecimal lifeTimeAwardValue;

    /**
     * Gets the value of the ytdAwardCount property.
     * 
     */
    public int getYTDAwardCount() {
        return ytdAwardCount;
    }

    /**
     * Sets the value of the ytdAwardCount property.
     * 
     */
    public void setYTDAwardCount(int value) {
        this.ytdAwardCount = value;
    }

    /**
     * Gets the value of the ytdAwardValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYTDAwardValue() {
        return ytdAwardValue;
    }

    /**
     * Sets the value of the ytdAwardValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYTDAwardValue(BigDecimal value) {
        this.ytdAwardValue = value;
    }

    /**
     * Gets the value of the lifeTimeAwardCount property.
     * 
     */
    public int getLifeTimeAwardCount() {
        return lifeTimeAwardCount;
    }

    /**
     * Sets the value of the lifeTimeAwardCount property.
     * 
     */
    public void setLifeTimeAwardCount(int value) {
        this.lifeTimeAwardCount = value;
    }

    /**
     * Gets the value of the lifeTimeAwardValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLifeTimeAwardValue() {
        return lifeTimeAwardValue;
    }

    /**
     * Sets the value of the lifeTimeAwardValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLifeTimeAwardValue(BigDecimal value) {
        this.lifeTimeAwardValue = value;
    }

}
