//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * NameDetails: The name of Loyalty Customer
 * 
 * <p>Java class for NameDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NameDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}NamePrefix" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}NameFirst"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}NameLast"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}NameMidl" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}NameSuffix" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameDetails", propOrder = {
    "namePrefix",
    "nameFirst",
    "nameLast",
    "nameMidl",
    "nameSuffix"
})
public class NameDetails {

    @XmlElement(name = "NamePrefix")
    protected String namePrefix;
    @XmlElement(name = "NameFirst", required = true)
    protected String nameFirst;
    @XmlElement(name = "NameLast", required = true)
    protected String nameLast;
    @XmlElement(name = "NameMidl")
    protected String nameMidl;
    @XmlElement(name = "NameSuffix")
    protected String nameSuffix;

    /**
     * NamePrefix: The name prefix used by the Loyalty Customer
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePrefix() {
        return namePrefix;
    }

    /**
     * Sets the value of the namePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePrefix(String value) {
        this.namePrefix = value;
    }

    /**
     * NameFirst: The first name of the Loyalty Customer
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameFirst() {
        return nameFirst;
    }

    /**
     * Sets the value of the nameFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameFirst(String value) {
        this.nameFirst = value;
    }

    /**
     * NameFirst: The last name of the Loyalty Customer
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLast() {
        return nameLast;
    }

    /**
     * Sets the value of the nameLast property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLast(String value) {
        this.nameLast = value;
    }

    /**
     * NameMidl: The middle name of the Loyalty Customer
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameMidl() {
        return nameMidl;
    }

    /**
     * Sets the value of the nameMidl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameMidl(String value) {
        this.nameMidl = value;
    }

    /**
     * NameSuffix: The name suffix used by the Loyalty Customer
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Sets the value of the nameSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSuffix(String value) {
        this.nameSuffix = value;
    }

}
