//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OfferDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfferDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OfferCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BonusRewardsEarned" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IsDeferedPoint" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="DeferedPointEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="EventType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfferDetails", propOrder = {
    "offerCode",
    "bonusRewardsEarned",
    "isDeferedPoint",
    "deferedPointEffectiveDate",
    "eventType"
})
public class OfferDetails {

    @XmlElement(name = "OfferCode", required = true)
    protected String offerCode;
    @XmlElement(name = "BonusRewardsEarned")
    protected BigDecimal bonusRewardsEarned;
    @XmlElement(name = "IsDeferedPoint")
    protected boolean isDeferedPoint;
    @XmlElement(name = "DeferedPointEffectiveDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deferedPointEffectiveDate;
    @XmlElement(name = "EventType")
    protected String eventType;

    /**
     * Gets the value of the offerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferCode() {
        return offerCode;
    }

    /**
     * Sets the value of the offerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferCode(String value) {
        this.offerCode = value;
    }

    /**
     * Gets the value of the bonusRewardsEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBonusRewardsEarned() {
        return bonusRewardsEarned;
    }

    /**
     * Sets the value of the bonusRewardsEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBonusRewardsEarned(BigDecimal value) {
        this.bonusRewardsEarned = value;
    }

    /**
     * Gets the value of the isDeferedPoint property.
     * 
     */
    public boolean isIsDeferedPoint() {
        return isDeferedPoint;
    }

    /**
     * Sets the value of the isDeferedPoint property.
     * 
     */
    public void setIsDeferedPoint(boolean value) {
        this.isDeferedPoint = value;
    }

    /**
     * Gets the value of the deferedPointEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeferedPointEffectiveDate() {
        return deferedPointEffectiveDate;
    }

    /**
     * Sets the value of the deferedPointEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeferedPointEffectiveDate(XMLGregorianCalendar value) {
        this.deferedPointEffectiveDate = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventType(String value) {
        this.eventType = value;
    }

}
