//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}RewardGroupCode" minOccurs="0"/>
 *         &lt;element name="TotalRewardsEarned" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="BonusRewardsEarned" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PendingRewardsEarned" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PendingBonusRewardsEarned" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="HoldPoints" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PendingHoldPoints" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="RewardStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rewardGroupCode",
    "totalRewardsEarned",
    "bonusRewardsEarned",
    "pendingRewardsEarned",
    "pendingBonusRewardsEarned",
    "holdPoints",
    "pendingHoldPoints",
    "rewardStatus"
})
@XmlRootElement(name = "TransactionRewardSummary")
public class TransactionRewardSummary {

    @XmlElement(name = "RewardGroupCode")
    protected String rewardGroupCode;
    @XmlElement(name = "TotalRewardsEarned")
    protected BigDecimal totalRewardsEarned;
    @XmlElement(name = "BonusRewardsEarned")
    protected BigDecimal bonusRewardsEarned;
    @XmlElement(name = "PendingRewardsEarned")
    protected BigDecimal pendingRewardsEarned;
    @XmlElement(name = "PendingBonusRewardsEarned")
    protected BigDecimal pendingBonusRewardsEarned;
    @XmlElement(name = "HoldPoints")
    protected BigDecimal holdPoints;
    @XmlElement(name = "PendingHoldPoints")
    protected BigDecimal pendingHoldPoints;
    @XmlElement(name = "RewardStatus")
    protected String rewardStatus;

    /**
     * Possible Values: TFS, MYMACYS, BLM, AMEX, USL, GPGM, DINE, MMON, BMON, BINT
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRewardGroupCode() {
        return rewardGroupCode;
    }

    /**
     * Sets the value of the rewardGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRewardGroupCode(String value) {
        this.rewardGroupCode = value;
    }

    /**
     * Gets the value of the totalRewardsEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalRewardsEarned() {
        return totalRewardsEarned;
    }

    /**
     * Sets the value of the totalRewardsEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalRewardsEarned(BigDecimal value) {
        this.totalRewardsEarned = value;
    }

    /**
     * Gets the value of the bonusRewardsEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBonusRewardsEarned() {
        return bonusRewardsEarned;
    }

    /**
     * Sets the value of the bonusRewardsEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBonusRewardsEarned(BigDecimal value) {
        this.bonusRewardsEarned = value;
    }

    /**
     * Gets the value of the pendingRewardsEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPendingRewardsEarned() {
        return pendingRewardsEarned;
    }

    /**
     * Sets the value of the pendingRewardsEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPendingRewardsEarned(BigDecimal value) {
        this.pendingRewardsEarned = value;
    }

    /**
     * Gets the value of the pendingBonusRewardsEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPendingBonusRewardsEarned() {
        return pendingBonusRewardsEarned;
    }

    /**
     * Sets the value of the pendingBonusRewardsEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPendingBonusRewardsEarned(BigDecimal value) {
        this.pendingBonusRewardsEarned = value;
    }

    /**
     * Gets the value of the holdPoints property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHoldPoints() {
        return holdPoints;
    }

    /**
     * Sets the value of the holdPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHoldPoints(BigDecimal value) {
        this.holdPoints = value;
    }

    /**
     * Gets the value of the pendingHoldPoints property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPendingHoldPoints() {
        return pendingHoldPoints;
    }

    /**
     * Sets the value of the pendingHoldPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPendingHoldPoints(BigDecimal value) {
        this.pendingHoldPoints = value;
    }

    /**
     * Gets the value of the rewardStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRewardStatus() {
        return rewardStatus;
    }

    /**
     * Sets the value of the rewardStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRewardStatus(String value) {
        this.rewardStatus = value;
    }

}
