//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dept" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="LineItemSeq" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="LineItemOriginalSeq" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ItemDesc" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ItemQty" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ItemPrice">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="14"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ItemTotalAmount">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="14"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}AssociateId" minOccurs="0"/>
 *         &lt;element name="Expired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Awarded" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}RewardGroupCode" minOccurs="0"/>
 *         &lt;element name="PercentageEarned" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="4"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PendingRewardsEarned" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="14"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BonusRewardsEarned" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="RewardsEarned" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="14"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}OfferDetails" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDetail", propOrder = {
    "dept",
    "clazz",
    "lineItemSeq",
    "lineItemOriginalSeq",
    "itemDesc",
    "itemQty",
    "itemPrice",
    "itemTotalAmount",
    "associateId",
    "expired",
    "awarded",
    "rewardGroupCode",
    "percentageEarned",
    "pendingRewardsEarned",
    "bonusRewardsEarned",
    "rewardsEarned",
    "offerDetails"
})
public class TransactionDetail {

    @XmlElement(name = "Dept")
    protected short dept;
    @XmlElement(name = "Class")
    protected short clazz;
    @XmlElement(name = "LineItemSeq")
    protected Integer lineItemSeq;
    @XmlElement(name = "LineItemOriginalSeq")
    protected Integer lineItemOriginalSeq;
    @XmlElement(name = "ItemDesc")
    protected String itemDesc;
    @XmlElement(name = "ItemQty")
    protected int itemQty;
    @XmlElement(name = "ItemPrice", required = true)
    protected BigDecimal itemPrice;
    @XmlElement(name = "ItemTotalAmount", required = true)
    protected BigDecimal itemTotalAmount;
    @XmlElement(name = "AssociateId")
    protected String associateId;
    @XmlElement(name = "Expired")
    protected boolean expired;
    @XmlElement(name = "Awarded")
    protected boolean awarded;
    @XmlElement(name = "RewardGroupCode")
    protected String rewardGroupCode;
    @XmlElement(name = "PercentageEarned")
    protected BigDecimal percentageEarned;
    @XmlElement(name = "PendingRewardsEarned")
    protected BigDecimal pendingRewardsEarned;
    @XmlElement(name = "BonusRewardsEarned")
    protected BigDecimal bonusRewardsEarned;
    @XmlElement(name = "RewardsEarned")
    protected BigDecimal rewardsEarned;
    @XmlElement(name = "OfferDetails")
    protected List<OfferDetails> offerDetails;

    /**
     * Gets the value of the dept property.
     * 
     */
    public short getDept() {
        return dept;
    }

    /**
     * Sets the value of the dept property.
     * 
     */
    public void setDept(short value) {
        this.dept = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     */
    public short getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     */
    public void setClazz(short value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the lineItemSeq property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLineItemSeq() {
        return lineItemSeq;
    }

    /**
     * Sets the value of the lineItemSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLineItemSeq(Integer value) {
        this.lineItemSeq = value;
    }

    /**
     * Gets the value of the lineItemOriginalSeq property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLineItemOriginalSeq() {
        return lineItemOriginalSeq;
    }

    /**
     * Sets the value of the lineItemOriginalSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLineItemOriginalSeq(Integer value) {
        this.lineItemOriginalSeq = value;
    }

    /**
     * Gets the value of the itemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * Sets the value of the itemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDesc(String value) {
        this.itemDesc = value;
    }

    /**
     * Gets the value of the itemQty property.
     * 
     */
    public int getItemQty() {
        return itemQty;
    }

    /**
     * Sets the value of the itemQty property.
     * 
     */
    public void setItemQty(int value) {
        this.itemQty = value;
    }

    /**
     * Gets the value of the itemPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * Sets the value of the itemPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemPrice(BigDecimal value) {
        this.itemPrice = value;
    }

    /**
     * Gets the value of the itemTotalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemTotalAmount() {
        return itemTotalAmount;
    }

    /**
     * Sets the value of the itemTotalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemTotalAmount(BigDecimal value) {
        this.itemTotalAmount = value;
    }

    /**
     * Gets the value of the associateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociateId() {
        return associateId;
    }

    /**
     * Sets the value of the associateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociateId(String value) {
        this.associateId = value;
    }

    /**
     * Gets the value of the expired property.
     * 
     */
    public boolean isExpired() {
        return expired;
    }

    /**
     * Sets the value of the expired property.
     * 
     */
    public void setExpired(boolean value) {
        this.expired = value;
    }

    /**
     * Gets the value of the awarded property.
     * 
     */
    public boolean isAwarded() {
        return awarded;
    }

    /**
     * Sets the value of the awarded property.
     * 
     */
    public void setAwarded(boolean value) {
        this.awarded = value;
    }

    /**
     * Possible Values: TFS, MYMACYS, BLM, AMEX, USL, GPGM, DINE, MMON, BMON, BINT
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRewardGroupCode() {
        return rewardGroupCode;
    }

    /**
     * Sets the value of the rewardGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRewardGroupCode(String value) {
        this.rewardGroupCode = value;
    }

    /**
     * Gets the value of the percentageEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentageEarned() {
        return percentageEarned;
    }

    /**
     * Sets the value of the percentageEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentageEarned(BigDecimal value) {
        this.percentageEarned = value;
    }

    /**
     * Gets the value of the pendingRewardsEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPendingRewardsEarned() {
        return pendingRewardsEarned;
    }

    /**
     * Sets the value of the pendingRewardsEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPendingRewardsEarned(BigDecimal value) {
        this.pendingRewardsEarned = value;
    }

    /**
     * Gets the value of the bonusRewardsEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBonusRewardsEarned() {
        return bonusRewardsEarned;
    }

    /**
     * Sets the value of the bonusRewardsEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBonusRewardsEarned(BigDecimal value) {
        this.bonusRewardsEarned = value;
    }

    /**
     * Gets the value of the rewardsEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRewardsEarned() {
        return rewardsEarned;
    }

    /**
     * Sets the value of the rewardsEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRewardsEarned(BigDecimal value) {
        this.rewardsEarned = value;
    }

    /**
     * Gets the value of the offerDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offerDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfferDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OfferDetails }
     * 
     * 
     */
    public List<OfferDetails> getOfferDetails() {
        if (offerDetails == null) {
            offerDetails = new ArrayList<OfferDetails>();
        }
        return this.offerDetails;
    }

}
