//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.10 at 04:53:00 PM IST 
//


package com.macys.loyalty.schemas.loyalty_transaction.ltytransactionrequest.v12_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.AccountIdentifier;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Advisory;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.CommunicationHeader;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.RewardAdjustment;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Stt;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}CommunicationHeader"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}CustomerIdentifier" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}Division"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}ProgramCode"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionRequest/v12_0}RewardAdjustment"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}AssociateId"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}AddedByApp"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}Stt" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}ReservationNum" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionRequest/v12_0}Advisory" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "communicationHeader",
    "customerIdentifier",
    "division",
    "programCode",
    "rewardAdjustment",
    "associateId",
    "addedByApp",
    "stt",
    "reservationNum",
    "advisory"
})
@XmlRootElement(name = "LtyCustServiceRewardReq")
public class LtyCustServiceRewardReq {

    @XmlElement(name = "CommunicationHeader", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected CommunicationHeader communicationHeader;
    @XmlElement(name = "CustomerIdentifier", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected List<AccountIdentifier> customerIdentifier;
    @XmlElement(name = "Division", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected short division;
    @XmlElement(name = "ProgramCode", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected String programCode;
    @XmlElement(name = "RewardAdjustment", required = true)
    protected RewardAdjustment rewardAdjustment;
    @XmlElement(name = "AssociateId", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected String associateId;
    @XmlElement(name = "AddedByApp", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected String addedByApp;
    @XmlElement(name = "Stt", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected Stt stt;
    @XmlElement(name = "ReservationNum", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected Long reservationNum;
    @XmlElement(name = "Advisory")
    protected List<Advisory> advisory;

    /**
     * Gets the value of the communicationHeader property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationHeader }
     *     
     */
    public CommunicationHeader getCommunicationHeader() {
        return communicationHeader;
    }

    /**
     * Sets the value of the communicationHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationHeader }
     *     
     */
    public void setCommunicationHeader(CommunicationHeader value) {
        this.communicationHeader = value;
    }

    /**
     * Gets the value of the customerIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountIdentifier }
     * 
     * 
     */
    public List<AccountIdentifier> getCustomerIdentifier() {
        if (customerIdentifier == null) {
            customerIdentifier = new ArrayList<AccountIdentifier>();
        }
        return this.customerIdentifier;
    }

    /**
     * Gets the value of the division property.
     * 
     */
    public short getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     */
    public void setDivision(short value) {
        this.division = value;
    }

    /**
     * ProgramCode - LTYTFS001, LTYMSR001, LTYBLM001, LTYMCY001, LTYUSL001, LTYDINE001, LTYGPGM001, LTYMMON001, LTYBMON001, LTYBINT001
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramCode() {
        return programCode;
    }

    /**
     * Sets the value of the programCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramCode(String value) {
        this.programCode = value;
    }

    /**
     * Gets the value of the rewardAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link RewardAdjustment }
     *     
     */
    public RewardAdjustment getRewardAdjustment() {
        return rewardAdjustment;
    }

    /**
     * Sets the value of the rewardAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link RewardAdjustment }
     *     
     */
    public void setRewardAdjustment(RewardAdjustment value) {
        this.rewardAdjustment = value;
    }

    /**
     * Gets the value of the associateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociateId() {
        return associateId;
    }

    /**
     * Sets the value of the associateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociateId(String value) {
        this.associateId = value;
    }

    /**
     * Gets the value of the addedByApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddedByApp() {
        return addedByApp;
    }

    /**
     * Sets the value of the addedByApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddedByApp(String value) {
        this.addedByApp = value;
    }

    /**
     * Gets the value of the stt property.
     * 
     * @return
     *     possible object is
     *     {@link Stt }
     *     
     */
    public Stt getStt() {
        return stt;
    }

    /**
     * Sets the value of the stt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stt }
     *     
     */
    public void setStt(Stt value) {
        this.stt = value;
    }

    /**
     * ReservationNum: The reservation number for FIL or RDS fulfillment channel
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getReservationNum() {
        return reservationNum;
    }

    /**
     * Sets the value of the reservationNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setReservationNum(Long value) {
        this.reservationNum = value;
    }

    /**
     * Gets the value of the advisory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the advisory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdvisory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Advisory }
     * 
     * 
     */
    public List<Advisory> getAdvisory() {
        if (advisory == null) {
            advisory = new ArrayList<Advisory>();
        }
        return this.advisory;
    }

}
