//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.AwardCard;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}AwardCard">
 *       &lt;sequence>
 *         &lt;element name="PreviousAwardReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RewardCarryoverAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AwardShipStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AwardCardStatus" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ACTIVE"/>
 *             &lt;enumeration value="EXPIRED"/>
 *             &lt;enumeration value="REPLACEMENT"/>
 *             &lt;enumeration value="REDEEMED"/>
 *             &lt;enumeration value="PENDING_REVERSAL"/>
 *             &lt;enumeration value="REVERSED"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "previousAwardReference",
    "rewardCarryoverAmount",
    "awardShipStatus"
})
@XmlRootElement(name = "AwardCards")
public class AwardCards
    extends AwardCard
{

    @XmlElement(name = "PreviousAwardReference")
    protected String previousAwardReference;
    @XmlElement(name = "RewardCarryoverAmount")
    protected BigDecimal rewardCarryoverAmount;
    @XmlElement(name = "AwardShipStatus")
    protected String awardShipStatus;
    @XmlAttribute(name = "AwardCardStatus", required = true)
    protected String awardCardStatus;

    /**
     * Gets the value of the previousAwardReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousAwardReference() {
        return previousAwardReference;
    }

    /**
     * Sets the value of the previousAwardReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousAwardReference(String value) {
        this.previousAwardReference = value;
    }

    /**
     * Gets the value of the rewardCarryoverAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRewardCarryoverAmount() {
        return rewardCarryoverAmount;
    }

    /**
     * Sets the value of the rewardCarryoverAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRewardCarryoverAmount(BigDecimal value) {
        this.rewardCarryoverAmount = value;
    }

    /**
     * Gets the value of the awardShipStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardShipStatus() {
        return awardShipStatus;
    }

    /**
     * Sets the value of the awardShipStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardShipStatus(String value) {
        this.awardShipStatus = value;
    }

    /**
     * Gets the value of the awardCardStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwardCardStatus() {
        return awardCardStatus;
    }

    /**
     * Sets the value of the awardCardStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwardCardStatus(String value) {
        this.awardCardStatus = value;
    }

}
