//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}ProgramCode"/>
 *         &lt;element name="ProgramEventName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}Dept"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}DeptDescription" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}Class" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}Vendor" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}MarkStyle" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}RewardPctRate"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "programCode",
    "programEventName",
    "dept",
    "deptDescription",
    "clazz",
    "vendor",
    "markStyle",
    "rewardPctRate",
    "description"
})
@XmlRootElement(name = "LtyLookupProgramOverride")
public class LtyLookupProgramOverride {

    @XmlElement(name = "ProgramCode", required = true)
    protected String programCode;
    @XmlElement(name = "ProgramEventName")
    protected String programEventName;
    @XmlElement(name = "Dept", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected short dept;
    @XmlElement(name = "DeptDescription", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected String deptDescription;
    @XmlElement(name = "Class", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected Short clazz;
    @XmlElement(name = "Vendor", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected Short vendor;
    @XmlElement(name = "MarkStyle", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected Integer markStyle;
    @XmlElement(name = "RewardPctRate", required = true)
    protected BigDecimal rewardPctRate;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the programCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramCode() {
        return programCode;
    }

    /**
     * Sets the value of the programCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramCode(String value) {
        this.programCode = value;
    }

    /**
     * Gets the value of the programEventName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramEventName() {
        return programEventName;
    }

    /**
     * Sets the value of the programEventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramEventName(String value) {
        this.programEventName = value;
    }

    /**
     * Dept: The department code of the merchandise.
     * 
     */
    public short getDept() {
        return dept;
    }

    /**
     * Sets the value of the dept property.
     * 
     */
    public void setDept(short value) {
        this.dept = value;
    }

    /**
     * Gets the value of the deptDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeptDescription() {
        return deptDescription;
    }

    /**
     * Sets the value of the deptDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeptDescription(String value) {
        this.deptDescription = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setClazz(Short value) {
        this.clazz = value;
    }

    /**
     * Vendor: Vendor code for an item purchased.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setVendor(Short value) {
        this.vendor = value;
    }

    /**
     * Markstyle: The markstyle of an item purchased.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMarkStyle() {
        return markStyle;
    }

    /**
     * Sets the value of the markStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMarkStyle(Integer value) {
        this.markStyle = value;
    }

    /**
     * Gets the value of the rewardPctRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRewardPctRate() {
        return rewardPctRate;
    }

    /**
     * Sets the value of the rewardPctRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRewardPctRate(BigDecimal value) {
        this.rewardPctRate = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
