//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Response;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}LtyLookupLoyaltySummary" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OperationResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ltyLookupLoyaltySummary",
    "operationResponse"
})
@XmlRootElement(name = "LtyLookupLoyaltySummaryResp")
public class LtyLookupLoyaltySummaryResp {

    @XmlElement(name = "LtyLookupLoyaltySummary")
    protected List<LtyLookupLoyaltySummary> ltyLookupLoyaltySummary;
    @XmlElement(name = "OperationResponse", required = true)
    protected Response operationResponse;

    /**
     * Gets the value of the ltyLookupLoyaltySummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ltyLookupLoyaltySummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLtyLookupLoyaltySummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LtyLookupLoyaltySummary }
     * 
     * 
     */
    public List<LtyLookupLoyaltySummary> getLtyLookupLoyaltySummary() {
        if (ltyLookupLoyaltySummary == null) {
            ltyLookupLoyaltySummary = new ArrayList<LtyLookupLoyaltySummary>();
        }
        return this.ltyLookupLoyaltySummary;
    }

    /**
     * Gets the value of the operationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getOperationResponse() {
        return operationResponse;
    }

    /**
     * Sets the value of the operationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setOperationResponse(Response value) {
        this.operationResponse = value;
    }

}
