//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OfferCode"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OfferMode"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OfferType" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}Division"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}ProgramCode"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OfferFrequency" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OfferRewardSpend" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Store" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OfferDeptInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OfferDesc" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}StoreEligible"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OnlineEligible"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}EffectiveDate"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}ExpiryDate"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}EventType" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}TierCode" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}PriceStatus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}TenderType" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}isPowerPoint" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}isIncremental" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}isPickADay" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}PresentmentStartTime" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}PresentmentEndTime" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}EmployeeExclusion" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}FixedOfferCombinable" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}OfferRank" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "offerCode",
    "offerMode",
    "offerType",
    "division",
    "programCode",
    "offerFrequency",
    "offerRewardSpend",
    "store",
    "offerDeptInfo",
    "offerDesc",
    "storeEligible",
    "onlineEligible",
    "effectiveDate",
    "expiryDate",
    "eventType",
    "tierCode",
    "priceStatus",
    "tenderType",
    "isPowerPoint",
    "isIncremental",
    "isPickADay",
    "presentmentStartTime",
    "presentmentEndTime",
    "employeeExclusion",
    "fixedOfferCombinable",
    "offerRank"
})
@XmlRootElement(name = "LtyLookupOffers")
public class LtyLookupOffers {

    @XmlElement(name = "OfferCode", required = true)
    protected String offerCode;
    @XmlElement(name = "OfferMode", required = true)
    protected String offerMode;
    @XmlElement(name = "OfferType")
    protected String offerType;
    @XmlElement(name = "Division")
    protected short division;
    @XmlElement(name = "ProgramCode", required = true)
    protected String programCode;
    @XmlElement(name = "OfferFrequency")
    protected OfferFrequency offerFrequency;
    @XmlElement(name = "OfferRewardSpend")
    protected List<OfferRewardSpend> offerRewardSpend;
    @XmlElement(name = "Store")
    protected List<String> store;
    @XmlElement(name = "OfferDeptInfo")
    protected List<OfferDeptInfo> offerDeptInfo;
    @XmlElement(name = "OfferDesc")
    protected String offerDesc;
    @XmlElement(name = "StoreEligible")
    protected boolean storeEligible;
    @XmlElement(name = "OnlineEligible")
    protected boolean onlineEligible;
    @XmlElement(name = "EffectiveDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(name = "ExpiryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(name = "EventType")
    protected String eventType;
    @XmlElement(name = "TierCode", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected String tierCode;
    @XmlElement(name = "PriceStatus", type = Short.class)
    protected List<Short> priceStatus;
    @XmlElement(name = "TenderType")
    protected String tenderType;
    protected Boolean isPowerPoint;
    protected Boolean isIncremental;
    protected Boolean isPickADay;
    @XmlElement(name = "PresentmentStartTime")
    protected String presentmentStartTime;
    @XmlElement(name = "PresentmentEndTime")
    protected String presentmentEndTime;
    @XmlElement(name = "EmployeeExclusion")
    protected Boolean employeeExclusion;
    @XmlElement(name = "FixedOfferCombinable")
    protected Boolean fixedOfferCombinable;
    @XmlElement(name = "OfferRank")
    protected Integer offerRank;

    /**
     * Gets the value of the offerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferCode() {
        return offerCode;
    }

    /**
     * Sets the value of the offerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferCode(String value) {
        this.offerCode = value;
    }

    /**
     * Gets the value of the offerMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferMode() {
        return offerMode;
    }

    /**
     * Sets the value of the offerMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferMode(String value) {
        this.offerMode = value;
    }

    /**
     * Gets the value of the offerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferType() {
        return offerType;
    }

    /**
     * Sets the value of the offerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferType(String value) {
        this.offerType = value;
    }

    /**
     * Gets the value of the division property.
     * 
     */
    public short getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     */
    public void setDivision(short value) {
        this.division = value;
    }

    /**
     * Gets the value of the programCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramCode() {
        return programCode;
    }

    /**
     * Sets the value of the programCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramCode(String value) {
        this.programCode = value;
    }

    /**
     * Gets the value of the offerFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link OfferFrequency }
     *     
     */
    public OfferFrequency getOfferFrequency() {
        return offerFrequency;
    }

    /**
     * Sets the value of the offerFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferFrequency }
     *     
     */
    public void setOfferFrequency(OfferFrequency value) {
        this.offerFrequency = value;
    }

    /**
     * Gets the value of the offerRewardSpend property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offerRewardSpend property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfferRewardSpend().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OfferRewardSpend }
     * 
     * 
     */
    public List<OfferRewardSpend> getOfferRewardSpend() {
        if (offerRewardSpend == null) {
            offerRewardSpend = new ArrayList<OfferRewardSpend>();
        }
        return this.offerRewardSpend;
    }

    /**
     * Gets the value of the store property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the store property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getStore() {
        if (store == null) {
            store = new ArrayList<String>();
        }
        return this.store;
    }

    /**
     * Gets the value of the offerDeptInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offerDeptInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfferDeptInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OfferDeptInfo }
     * 
     * 
     */
    public List<OfferDeptInfo> getOfferDeptInfo() {
        if (offerDeptInfo == null) {
            offerDeptInfo = new ArrayList<OfferDeptInfo>();
        }
        return this.offerDeptInfo;
    }

    /**
     * Gets the value of the offerDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferDesc() {
        return offerDesc;
    }

    /**
     * Sets the value of the offerDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferDesc(String value) {
        this.offerDesc = value;
    }

    /**
     * Gets the value of the storeEligible property.
     * 
     */
    public boolean isStoreEligible() {
        return storeEligible;
    }

    /**
     * Sets the value of the storeEligible property.
     * 
     */
    public void setStoreEligible(boolean value) {
        this.storeEligible = value;
    }

    /**
     * Gets the value of the onlineEligible property.
     * 
     */
    public boolean isOnlineEligible() {
        return onlineEligible;
    }

    /**
     * Sets the value of the onlineEligible property.
     * 
     */
    public void setOnlineEligible(boolean value) {
        this.onlineEligible = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventType(String value) {
        this.eventType = value;
    }

    /**
     * TierCode: The tier of the Loyalty Customer. Bloomingdale: BLMT001, BLMT002, BLMT003.  Macys: PREMIER_ELITE, ELITE, PREFFERED
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTierCode() {
        return tierCode;
    }

    /**
     * Sets the value of the tierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTierCode(String value) {
        this.tierCode = value;
    }

    /**
     * Gets the value of the priceStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriceStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getPriceStatus() {
        if (priceStatus == null) {
            priceStatus = new ArrayList<Short>();
        }
        return this.priceStatus;
    }

    /**
     * Gets the value of the tenderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderType() {
        return tenderType;
    }

    /**
     * Sets the value of the tenderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderType(String value) {
        this.tenderType = value;
    }

    /**
     * Gets the value of the isPowerPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPowerPoint() {
        return isPowerPoint;
    }

    /**
     * Sets the value of the isPowerPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPowerPoint(Boolean value) {
        this.isPowerPoint = value;
    }

    /**
     * Gets the value of the isIncremental property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsIncremental() {
        return isIncremental;
    }

    /**
     * Sets the value of the isIncremental property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsIncremental(Boolean value) {
        this.isIncremental = value;
    }

    /**
     * Gets the value of the isPickADay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPickADay() {
        return isPickADay;
    }

    /**
     * Sets the value of the isPickADay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPickADay(Boolean value) {
        this.isPickADay = value;
    }

    /**
     * Gets the value of the presentmentStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentmentStartTime() {
        return presentmentStartTime;
    }

    /**
     * Sets the value of the presentmentStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentmentStartTime(String value) {
        this.presentmentStartTime = value;
    }

    /**
     * Gets the value of the presentmentEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentmentEndTime() {
        return presentmentEndTime;
    }

    /**
     * Sets the value of the presentmentEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentmentEndTime(String value) {
        this.presentmentEndTime = value;
    }

    /**
     * Gets the value of the employeeExclusion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEmployeeExclusion() {
        return employeeExclusion;
    }

    /**
     * Sets the value of the employeeExclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEmployeeExclusion(Boolean value) {
        this.employeeExclusion = value;
    }

    /**
     * Gets the value of the fixedOfferCombinable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFixedOfferCombinable() {
        return fixedOfferCombinable;
    }

    /**
     * Sets the value of the fixedOfferCombinable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFixedOfferCombinable(Boolean value) {
        this.fixedOfferCombinable = value;
    }

    /**
     * Gets the value of the offerRank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOfferRank() {
        return offerRank;
    }

    /**
     * Sets the value of the offerRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOfferRank(Integer value) {
        this.offerRank = value;
    }

}
