//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Attribute;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.AwardSummary;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.FaultResponse;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Points;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.ProgramInfo;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Response;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Stt;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Tender;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReturnQuantity_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "ReturnQuantity");
    private final static QName _PointsToNextAward_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "PointsToNextAward");
    private final static QName _RecordGroupSeq_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "RecordGroupSeq");
    private final static QName _ProgramCode_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "ProgramCode");
    private final static QName _Vendor_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "Vendor");
    private final static QName _IsIncremental_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "isIncremental");
    private final static QName _TransactionTender_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "TransactionTender");
    private final static QName _OperationResponse_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "OperationResponse");
    private final static QName _EffectiveDate_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "EffectiveDate");
    private final static QName _FixedOfferCombinable_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "FixedOfferCombinable");
    private final static QName _RewardAttribute_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "RewardAttribute");
    private final static QName _OfferType_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "OfferType");
    private final static QName _EmployeeExclusion_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "EmployeeExclusion");
    private final static QName _PostVoidStt_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "PostVoidStt");
    private final static QName _OfferRank_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "OfferRank");
    private final static QName _SalescheckNum_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "SalescheckNum");
    private final static QName _Points_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "Points");
    private final static QName _GroupItemCount_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "GroupItemCount");
    private final static QName _TenderType_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "TenderType");
    private final static QName _IsPending_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "IsPending");
    private final static QName _Multiplier_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "Multiplier");
    private final static QName _TenderReference_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "TenderReference");
    private final static QName _IsExpired_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "IsExpired");
    private final static QName _TxnSpendMax_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "TxnSpendMax");
    private final static QName _OfferMode_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "OfferMode");
    private final static QName _OfferDesc_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "OfferDesc");
    private final static QName _Class_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "Class");
    private final static QName _EventType_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "EventType");
    private final static QName _AwardSummary_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "AwardSummary");
    private final static QName _ExpiryDate_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "ExpiryDate");
    private final static QName _OnlineEligible_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "OnlineEligible");
    private final static QName _IsPowerPoint_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "isPowerPoint");
    private final static QName _TenderCode_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "TenderCode");
    private final static QName _BonusRewardPctRate_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "BonusRewardPctRate");
    private final static QName _ProgramInfo_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "ProgramInfo");
    private final static QName _HoldpointEffectiveDate_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "HoldpointEffectiveDate");
    private final static QName _TenderCategory_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "TenderCategory");
    private final static QName _ValidForUse_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "ValidForUse");
    private final static QName _DeptSpendMax_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "DeptSpendMax");
    private final static QName _LtyFault_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "LtyFault");
    private final static QName _IsAwarded_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "isAwarded");
    private final static QName _Dept_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "Dept");
    private final static QName _DeptSpendMin_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "DeptSpendMin");
    private final static QName _PresentmentStartTime_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "PresentmentStartTime");
    private final static QName _TxnSpendMin_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "TxnSpendMin");
    private final static QName _PresentmentEndTime_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "PresentmentEndTime");
    private final static QName _Division_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "Division");
    private final static QName _PriceStatus_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "PriceStatus");
    private final static QName _OfflineRetryFlag_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "OfflineRetryFlag");
    private final static QName _IsTransient_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "IsTransient");
    private final static QName _RewardAmount_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "RewardAmount");
    private final static QName _PaymentAmount_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "PaymentAmount");
    private final static QName _MarkStyle_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "MarkStyle");
    private final static QName _StoreEligible_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "StoreEligible");
    private final static QName _IsHoldPoint_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "isHoldPoint");
    private final static QName _BonusRewardAmount_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "BonusRewardAmount");
    private final static QName _RecordGroup_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "RecordGroup");
    private final static QName _Stt_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "Stt");
    private final static QName _IsPickADay_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "isPickADay");
    private final static QName _FinancialSaleQuantity_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "FinancialSaleQuantity");
    private final static QName _ReservationNum_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "ReservationNum");
    private final static QName _RewardPctRate_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "RewardPctRate");
    private final static QName _OfferCode_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", "OfferCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LtyLookupOfferListResp }
     * 
     */
    public LtyLookupOfferListResp createLtyLookupOfferListResp() {
        return new LtyLookupOfferListResp();
    }

    /**
     * Create an instance of {@link LtyLookupOfferList }
     * 
     */
    public LtyLookupOfferList createLtyLookupOfferList() {
        return new LtyLookupOfferList();
    }

    /**
     * Create an instance of {@link TransactionLine }
     * 
     */
    public TransactionLine createTransactionLine() {
        return new TransactionLine();
    }

    /**
     * Create an instance of {@link Reward }
     * 
     */
    public Reward createReward() {
        return new Reward();
    }

    /**
     * Create an instance of {@link RewardOffer }
     * 
     */
    public RewardOffer createRewardOffer() {
        return new RewardOffer();
    }

    /**
     * Create an instance of {@link LtyProgramStatusUpdateResp }
     * 
     */
    public LtyProgramStatusUpdateResp createLtyProgramStatusUpdateResp() {
        return new LtyProgramStatusUpdateResp();
    }

    /**
     * Create an instance of {@link LtyLookupOffers }
     * 
     */
    public LtyLookupOffers createLtyLookupOffers() {
        return new LtyLookupOffers();
    }

    /**
     * Create an instance of {@link OfferFrequency }
     * 
     */
    public OfferFrequency createOfferFrequency() {
        return new OfferFrequency();
    }

    /**
     * Create an instance of {@link OfferRewardSpend }
     * 
     */
    public OfferRewardSpend createOfferRewardSpend() {
        return new OfferRewardSpend();
    }

    /**
     * Create an instance of {@link OfferDeptInfo }
     * 
     */
    public OfferDeptInfo createOfferDeptInfo() {
        return new OfferDeptInfo();
    }

    /**
     * Create an instance of {@link LtyLookupTransactionResp }
     * 
     */
    public LtyLookupTransactionResp createLtyLookupTransactionResp() {
        return new LtyLookupTransactionResp();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link TransactionHeader }
     * 
     */
    public TransactionHeader createTransactionHeader() {
        return new TransactionHeader();
    }

    /**
     * Create an instance of {@link AwardActivity }
     * 
     */
    public AwardActivity createAwardActivity() {
        return new AwardActivity();
    }

    /**
     * Create an instance of {@link RewardSummary }
     * 
     */
    public RewardSummary createRewardSummary() {
        return new RewardSummary();
    }

    /**
     * Create an instance of {@link LtyUpdtInfoResp }
     * 
     */
    public LtyUpdtInfoResp createLtyUpdtInfoResp() {
        return new LtyUpdtInfoResp();
    }

    /**
     * Create an instance of {@link AcctProgramInfo }
     * 
     */
    public AcctProgramInfo createAcctProgramInfo() {
        return new AcctProgramInfo();
    }

    /**
     * Create an instance of {@link CustomerDetail }
     * 
     */
    public CustomerDetail createCustomerDetail() {
        return new CustomerDetail();
    }

    /**
     * Create an instance of {@link TxnSpend }
     * 
     */
    public TxnSpend createTxnSpend() {
        return new TxnSpend();
    }

    /**
     * Create an instance of {@link LtyLookupLoyaltySummaryResp }
     * 
     */
    public LtyLookupLoyaltySummaryResp createLtyLookupLoyaltySummaryResp() {
        return new LtyLookupLoyaltySummaryResp();
    }

    /**
     * Create an instance of {@link LtyLookupLoyaltySummary }
     * 
     */
    public LtyLookupLoyaltySummary createLtyLookupLoyaltySummary() {
        return new LtyLookupLoyaltySummary();
    }

    /**
     * Create an instance of {@link CustomerInfo }
     * 
     */
    public CustomerInfo createCustomerInfo() {
        return new CustomerInfo();
    }

    /**
     * Create an instance of {@link Program }
     * 
     */
    public Program createProgram() {
        return new Program();
    }

    /**
     * Create an instance of {@link DeptSpend }
     * 
     */
    public DeptSpend createDeptSpend() {
        return new DeptSpend();
    }

    /**
     * Create an instance of {@link LtyLookupProgramOverride }
     * 
     */
    public LtyLookupProgramOverride createLtyLookupProgramOverride() {
        return new LtyLookupProgramOverride();
    }

    /**
     * Create an instance of {@link LtyPADLookupResp }
     * 
     */
    public LtyPADLookupResp createLtyPADLookupResp() {
        return new LtyPADLookupResp();
    }

    /**
     * Create an instance of {@link PADAvailability }
     * 
     */
    public PADAvailability createPADAvailability() {
        return new PADAvailability();
    }

    /**
     * Create an instance of {@link PADScheduledDays }
     * 
     */
    public PADScheduledDays createPADScheduledDays() {
        return new PADScheduledDays();
    }

    /**
     * Create an instance of {@link PADOffer }
     * 
     */
    public PADOffer createPADOffer() {
        return new PADOffer();
    }

    /**
     * Create an instance of {@link TransactionList }
     * 
     */
    public TransactionList createTransactionList() {
        return new TransactionList();
    }

    /**
     * Create an instance of {@link LtyLookupOfferInfoResp }
     * 
     */
    public LtyLookupOfferInfoResp createLtyLookupOfferInfoResp() {
        return new LtyLookupOfferInfoResp();
    }

    /**
     * Create an instance of {@link ProgramDetail }
     * 
     */
    public ProgramDetail createProgramDetail() {
        return new ProgramDetail();
    }

    /**
     * Create an instance of {@link AwardCards }
     * 
     */
    public AwardCards createAwardCards() {
        return new AwardCards();
    }

    /**
     * Create an instance of {@link LtyLookupLoyaltyCusInfoResp }
     * 
     */
    public LtyLookupLoyaltyCusInfoResp createLtyLookupLoyaltyCusInfoResp() {
        return new LtyLookupLoyaltyCusInfoResp();
    }

    /**
     * Create an instance of {@link OfferRewardDetail }
     * 
     */
    public OfferRewardDetail createOfferRewardDetail() {
        return new OfferRewardDetail();
    }

    /**
     * Create an instance of {@link LtyLookupProgramOverrideResp }
     * 
     */
    public LtyLookupProgramOverrideResp createLtyLookupProgramOverrideResp() {
        return new LtyLookupProgramOverrideResp();
    }

    /**
     * Create an instance of {@link LtyLookupLoyaltyDetailResp }
     * 
     */
    public LtyLookupLoyaltyDetailResp createLtyLookupLoyaltyDetailResp() {
        return new LtyLookupLoyaltyDetailResp();
    }

    /**
     * Create an instance of {@link LtyLookupLoyaltyDetail }
     * 
     */
    public LtyLookupLoyaltyDetail createLtyLookupLoyaltyDetail() {
        return new LtyLookupLoyaltyDetail();
    }

    /**
     * Create an instance of {@link TransactionPayment }
     * 
     */
    public TransactionPayment createTransactionPayment() {
        return new TransactionPayment();
    }

    /**
     * Create an instance of {@link Award }
     * 
     */
    public Award createAward() {
        return new Award();
    }

    /**
     * Create an instance of {@link DeptInfo }
     * 
     */
    public DeptInfo createDeptInfo() {
        return new DeptInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "ReturnQuantity")
    public JAXBElement<Integer> createReturnQuantity(Integer value) {
        return new JAXBElement<Integer>(_ReturnQuantity_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Points }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "PointsToNextAward")
    public JAXBElement<Points> createPointsToNextAward(Points value) {
        return new JAXBElement<Points>(_PointsToNextAward_QNAME, Points.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "RecordGroupSeq")
    public JAXBElement<Integer> createRecordGroupSeq(Integer value) {
        return new JAXBElement<Integer>(_RecordGroupSeq_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "ProgramCode")
    public JAXBElement<String> createProgramCode(String value) {
        return new JAXBElement<String>(_ProgramCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "Vendor")
    public JAXBElement<Short> createVendor(Short value) {
        return new JAXBElement<Short>(_Vendor_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "isIncremental")
    public JAXBElement<Boolean> createIsIncremental(Boolean value) {
        return new JAXBElement<Boolean>(_IsIncremental_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tender }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "TransactionTender")
    public JAXBElement<Tender> createTransactionTender(Tender value) {
        return new JAXBElement<Tender>(_TransactionTender_QNAME, Tender.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "OperationResponse")
    public JAXBElement<Response> createOperationResponse(Response value) {
        return new JAXBElement<Response>(_OperationResponse_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "EffectiveDate")
    public JAXBElement<XMLGregorianCalendar> createEffectiveDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EffectiveDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "FixedOfferCombinable")
    public JAXBElement<Boolean> createFixedOfferCombinable(Boolean value) {
        return new JAXBElement<Boolean>(_FixedOfferCombinable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Attribute }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "RewardAttribute")
    public JAXBElement<Attribute> createRewardAttribute(Attribute value) {
        return new JAXBElement<Attribute>(_RewardAttribute_QNAME, Attribute.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "OfferType")
    public JAXBElement<String> createOfferType(String value) {
        return new JAXBElement<String>(_OfferType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "EmployeeExclusion")
    public JAXBElement<Boolean> createEmployeeExclusion(Boolean value) {
        return new JAXBElement<Boolean>(_EmployeeExclusion_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Stt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "PostVoidStt")
    public JAXBElement<Stt> createPostVoidStt(Stt value) {
        return new JAXBElement<Stt>(_PostVoidStt_QNAME, Stt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "OfferRank")
    public JAXBElement<Integer> createOfferRank(Integer value) {
        return new JAXBElement<Integer>(_OfferRank_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "SalescheckNum")
    public JAXBElement<String> createSalescheckNum(String value) {
        return new JAXBElement<String>(_SalescheckNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "Points")
    public JAXBElement<BigDecimal> createPoints(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Points_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "GroupItemCount")
    public JAXBElement<Integer> createGroupItemCount(Integer value) {
        return new JAXBElement<Integer>(_GroupItemCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "TenderType")
    public JAXBElement<String> createTenderType(String value) {
        return new JAXBElement<String>(_TenderType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "IsPending")
    public JAXBElement<Boolean> createIsPending(Boolean value) {
        return new JAXBElement<Boolean>(_IsPending_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "Multiplier")
    public JAXBElement<BigDecimal> createMultiplier(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Multiplier_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "TenderReference")
    public JAXBElement<String> createTenderReference(String value) {
        return new JAXBElement<String>(_TenderReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "IsExpired")
    public JAXBElement<Boolean> createIsExpired(Boolean value) {
        return new JAXBElement<Boolean>(_IsExpired_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "TxnSpendMax")
    public JAXBElement<BigDecimal> createTxnSpendMax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TxnSpendMax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "OfferMode")
    public JAXBElement<String> createOfferMode(String value) {
        return new JAXBElement<String>(_OfferMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "OfferDesc")
    public JAXBElement<String> createOfferDesc(String value) {
        return new JAXBElement<String>(_OfferDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "Class")
    public JAXBElement<Short> createClass(Short value) {
        return new JAXBElement<Short>(_Class_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "EventType")
    public JAXBElement<String> createEventType(String value) {
        return new JAXBElement<String>(_EventType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AwardSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "AwardSummary")
    public JAXBElement<AwardSummary> createAwardSummary(AwardSummary value) {
        return new JAXBElement<AwardSummary>(_AwardSummary_QNAME, AwardSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "ExpiryDate")
    public JAXBElement<XMLGregorianCalendar> createExpiryDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ExpiryDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "OnlineEligible")
    public JAXBElement<Boolean> createOnlineEligible(Boolean value) {
        return new JAXBElement<Boolean>(_OnlineEligible_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "isPowerPoint")
    public JAXBElement<Boolean> createIsPowerPoint(Boolean value) {
        return new JAXBElement<Boolean>(_IsPowerPoint_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "TenderCode")
    public JAXBElement<String> createTenderCode(String value) {
        return new JAXBElement<String>(_TenderCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "BonusRewardPctRate")
    public JAXBElement<BigDecimal> createBonusRewardPctRate(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BonusRewardPctRate_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "ProgramInfo")
    public JAXBElement<ProgramInfo> createProgramInfo(ProgramInfo value) {
        return new JAXBElement<ProgramInfo>(_ProgramInfo_QNAME, ProgramInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "HoldpointEffectiveDate")
    public JAXBElement<XMLGregorianCalendar> createHoldpointEffectiveDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_HoldpointEffectiveDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "TenderCategory")
    public JAXBElement<String> createTenderCategory(String value) {
        return new JAXBElement<String>(_TenderCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "ValidForUse")
    public JAXBElement<Boolean> createValidForUse(Boolean value) {
        return new JAXBElement<Boolean>(_ValidForUse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "DeptSpendMax")
    public JAXBElement<BigDecimal> createDeptSpendMax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DeptSpendMax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "LtyFault")
    public JAXBElement<FaultResponse> createLtyFault(FaultResponse value) {
        return new JAXBElement<FaultResponse>(_LtyFault_QNAME, FaultResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "isAwarded")
    public JAXBElement<Boolean> createIsAwarded(Boolean value) {
        return new JAXBElement<Boolean>(_IsAwarded_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "Dept")
    public JAXBElement<Short> createDept(Short value) {
        return new JAXBElement<Short>(_Dept_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "DeptSpendMin")
    public JAXBElement<BigDecimal> createDeptSpendMin(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DeptSpendMin_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "PresentmentStartTime")
    public JAXBElement<String> createPresentmentStartTime(String value) {
        return new JAXBElement<String>(_PresentmentStartTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "TxnSpendMin")
    public JAXBElement<BigDecimal> createTxnSpendMin(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TxnSpendMin_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "PresentmentEndTime")
    public JAXBElement<String> createPresentmentEndTime(String value) {
        return new JAXBElement<String>(_PresentmentEndTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "Division")
    public JAXBElement<Short> createDivision(Short value) {
        return new JAXBElement<Short>(_Division_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "PriceStatus")
    public JAXBElement<Short> createPriceStatus(Short value) {
        return new JAXBElement<Short>(_PriceStatus_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "OfflineRetryFlag")
    public JAXBElement<String> createOfflineRetryFlag(String value) {
        return new JAXBElement<String>(_OfflineRetryFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "IsTransient")
    public JAXBElement<Boolean> createIsTransient(Boolean value) {
        return new JAXBElement<Boolean>(_IsTransient_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "RewardAmount")
    public JAXBElement<BigDecimal> createRewardAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RewardAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "PaymentAmount")
    public JAXBElement<BigDecimal> createPaymentAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PaymentAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "MarkStyle")
    public JAXBElement<Integer> createMarkStyle(Integer value) {
        return new JAXBElement<Integer>(_MarkStyle_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "StoreEligible")
    public JAXBElement<Boolean> createStoreEligible(Boolean value) {
        return new JAXBElement<Boolean>(_StoreEligible_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "isHoldPoint")
    public JAXBElement<Boolean> createIsHoldPoint(Boolean value) {
        return new JAXBElement<Boolean>(_IsHoldPoint_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "BonusRewardAmount")
    public JAXBElement<BigDecimal> createBonusRewardAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BonusRewardAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "RecordGroup")
    public JAXBElement<Integer> createRecordGroup(Integer value) {
        return new JAXBElement<Integer>(_RecordGroup_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Stt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "Stt")
    public JAXBElement<Stt> createStt(Stt value) {
        return new JAXBElement<Stt>(_Stt_QNAME, Stt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "isPickADay")
    public JAXBElement<Boolean> createIsPickADay(Boolean value) {
        return new JAXBElement<Boolean>(_IsPickADay_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "FinancialSaleQuantity")
    public JAXBElement<Integer> createFinancialSaleQuantity(Integer value) {
        return new JAXBElement<Integer>(_FinancialSaleQuantity_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "ReservationNum")
    public JAXBElement<String> createReservationNum(String value) {
        return new JAXBElement<String>(_ReservationNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "RewardPctRate")
    public JAXBElement<BigDecimal> createRewardPctRate(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RewardPctRate_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0", name = "OfferCode")
    public JAXBElement<String> createOfferCode(String value) {
        return new JAXBElement<String>(_OfferCode_QNAME, String.class, null, value);
    }

}
