//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}RecordGroupSeq" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}Dept"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}Class" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}Vendor" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}MarkStyle" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}GroupItemCount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recordGroupSeq",
    "dept",
    "clazz",
    "vendor",
    "markStyle",
    "groupItemCount"
})
@XmlRootElement(name = "OfferDeptInfo")
public class OfferDeptInfo {

    @XmlElement(name = "RecordGroupSeq")
    protected Integer recordGroupSeq;
    @XmlElement(name = "Dept")
    protected short dept;
    @XmlElement(name = "Class")
    protected Short clazz;
    @XmlElement(name = "Vendor")
    protected Short vendor;
    @XmlElement(name = "MarkStyle")
    protected Integer markStyle;
    @XmlElement(name = "GroupItemCount")
    protected Integer groupItemCount;

    /**
     * Gets the value of the recordGroupSeq property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecordGroupSeq() {
        return recordGroupSeq;
    }

    /**
     * Sets the value of the recordGroupSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecordGroupSeq(Integer value) {
        this.recordGroupSeq = value;
    }

    /**
     * Gets the value of the dept property.
     * 
     */
    public short getDept() {
        return dept;
    }

    /**
     * Sets the value of the dept property.
     * 
     */
    public void setDept(short value) {
        this.dept = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setClazz(Short value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setVendor(Short value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the markStyle property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMarkStyle() {
        return markStyle;
    }

    /**
     * Sets the value of the markStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMarkStyle(Integer value) {
        this.markStyle = value;
    }

    /**
     * Gets the value of the groupItemCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupItemCount() {
        return groupItemCount;
    }

    /**
     * Sets the value of the groupItemCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupItemCount(Integer value) {
        this.groupItemCount = value;
    }

}
