//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.AccountIdentifier;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}CustomerIdentifier"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}RewardGroupCode"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}RewardAmount"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}RewardPctRate"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}BonusRewardAmount"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}BonusRewardPctRate"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}HoldpointEffectiveDate" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}IsTransient"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}IsPending"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}IsExpired"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}isAwarded"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}RewardOffer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}ReturnQuantity" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.account/LtyAccountResponse/v12_0}FinancialSaleQuantity" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerIdentifier",
    "rewardGroupCode",
    "rewardAmount",
    "rewardPctRate",
    "bonusRewardAmount",
    "bonusRewardPctRate",
    "holdpointEffectiveDate",
    "isTransient",
    "isPending",
    "isExpired",
    "isAwarded",
    "rewardOffer",
    "returnQuantity",
    "financialSaleQuantity"
})
@XmlRootElement(name = "Reward")
public class Reward {

    @XmlElement(name = "CustomerIdentifier", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected AccountIdentifier customerIdentifier;
    @XmlElement(name = "RewardGroupCode", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected String rewardGroupCode;
    @XmlElement(name = "RewardAmount", required = true)
    protected BigDecimal rewardAmount;
    @XmlElement(name = "RewardPctRate", required = true)
    protected BigDecimal rewardPctRate;
    @XmlElement(name = "BonusRewardAmount", required = true)
    protected BigDecimal bonusRewardAmount;
    @XmlElement(name = "BonusRewardPctRate", required = true)
    protected BigDecimal bonusRewardPctRate;
    @XmlElement(name = "HoldpointEffectiveDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar holdpointEffectiveDate;
    @XmlElement(name = "IsTransient")
    protected boolean isTransient;
    @XmlElement(name = "IsPending")
    protected boolean isPending;
    @XmlElement(name = "IsExpired")
    protected boolean isExpired;
    protected boolean isAwarded;
    @XmlElement(name = "RewardOffer")
    protected List<RewardOffer> rewardOffer;
    @XmlElement(name = "ReturnQuantity")
    protected Integer returnQuantity;
    @XmlElement(name = "FinancialSaleQuantity")
    protected Integer financialSaleQuantity;

    /**
     * Gets the value of the customerIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link AccountIdentifier }
     *     
     */
    public AccountIdentifier getCustomerIdentifier() {
        return customerIdentifier;
    }

    /**
     * Sets the value of the customerIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountIdentifier }
     *     
     */
    public void setCustomerIdentifier(AccountIdentifier value) {
        this.customerIdentifier = value;
    }

    /**
     * Possible Values: TFS, MYMACYS, BLM, AMEX, USL, GPGM, DINE, MMON, BMON, BINT
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRewardGroupCode() {
        return rewardGroupCode;
    }

    /**
     * Sets the value of the rewardGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRewardGroupCode(String value) {
        this.rewardGroupCode = value;
    }

    /**
     * Gets the value of the rewardAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRewardAmount() {
        return rewardAmount;
    }

    /**
     * Sets the value of the rewardAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRewardAmount(BigDecimal value) {
        this.rewardAmount = value;
    }

    /**
     * Gets the value of the rewardPctRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRewardPctRate() {
        return rewardPctRate;
    }

    /**
     * Sets the value of the rewardPctRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRewardPctRate(BigDecimal value) {
        this.rewardPctRate = value;
    }

    /**
     * Gets the value of the bonusRewardAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBonusRewardAmount() {
        return bonusRewardAmount;
    }

    /**
     * Sets the value of the bonusRewardAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBonusRewardAmount(BigDecimal value) {
        this.bonusRewardAmount = value;
    }

    /**
     * Gets the value of the bonusRewardPctRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBonusRewardPctRate() {
        return bonusRewardPctRate;
    }

    /**
     * Sets the value of the bonusRewardPctRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBonusRewardPctRate(BigDecimal value) {
        this.bonusRewardPctRate = value;
    }

    /**
     * Gets the value of the holdpointEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHoldpointEffectiveDate() {
        return holdpointEffectiveDate;
    }

    /**
     * Sets the value of the holdpointEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHoldpointEffectiveDate(XMLGregorianCalendar value) {
        this.holdpointEffectiveDate = value;
    }

    /**
     * Gets the value of the isTransient property.
     * 
     */
    public boolean isIsTransient() {
        return isTransient;
    }

    /**
     * Sets the value of the isTransient property.
     * 
     */
    public void setIsTransient(boolean value) {
        this.isTransient = value;
    }

    /**
     * Gets the value of the isPending property.
     * 
     */
    public boolean isIsPending() {
        return isPending;
    }

    /**
     * Sets the value of the isPending property.
     * 
     */
    public void setIsPending(boolean value) {
        this.isPending = value;
    }

    /**
     * Gets the value of the isExpired property.
     * 
     */
    public boolean isIsExpired() {
        return isExpired;
    }

    /**
     * Sets the value of the isExpired property.
     * 
     */
    public void setIsExpired(boolean value) {
        this.isExpired = value;
    }

    /**
     * Gets the value of the isAwarded property.
     * 
     */
    public boolean isIsAwarded() {
        return isAwarded;
    }

    /**
     * Sets the value of the isAwarded property.
     * 
     */
    public void setIsAwarded(boolean value) {
        this.isAwarded = value;
    }

    /**
     * Gets the value of the rewardOffer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rewardOffer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRewardOffer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RewardOffer }
     * 
     * 
     */
    public List<RewardOffer> getRewardOffer() {
        if (rewardOffer == null) {
            rewardOffer = new ArrayList<RewardOffer>();
        }
        return this.rewardOffer;
    }

    /**
     * Gets the value of the returnQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReturnQuantity() {
        return returnQuantity;
    }

    /**
     * Sets the value of the returnQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReturnQuantity(Integer value) {
        this.returnQuantity = value;
    }

    /**
     * Gets the value of the financialSaleQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFinancialSaleQuantity() {
        return financialSaleQuantity;
    }

    /**
     * Sets the value of the financialSaleQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFinancialSaleQuantity(Integer value) {
        this.financialSaleQuantity = value;
    }

}
