//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 05:37:24 PM IST 
//


package com.macys.loyalty.schemas.loyalty_account.ltyaccountresponse.v12_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.CurrentBalance;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}RewardGroupCode"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}CurrentBalance"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}YTDRewardEarned" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}LifeTimeRewardEarned" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rewardGroupCode",
    "currentBalance",
    "ytdRewardEarned",
    "lifeTimeRewardEarned"
})
@XmlRootElement(name = "RewardSummary")
public class RewardSummary {

    @XmlElement(name = "RewardGroupCode", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected String rewardGroupCode;
    @XmlElement(name = "CurrentBalance", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected CurrentBalance currentBalance;
    @XmlElement(name = "YTDRewardEarned", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected BigDecimal ytdRewardEarned;
    @XmlElement(name = "LifeTimeRewardEarned", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected BigDecimal lifeTimeRewardEarned;

    /**
     * Possible Values: TFS, MYMACYS, BLM, AMEX, USL, GPGM, DINE, MMON, BMON, BINT
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRewardGroupCode() {
        return rewardGroupCode;
    }

    /**
     * Sets the value of the rewardGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRewardGroupCode(String value) {
        this.rewardGroupCode = value;
    }

    /**
     * Gets the value of the currentBalance property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentBalance }
     *     
     */
    public CurrentBalance getCurrentBalance() {
        return currentBalance;
    }

    /**
     * Sets the value of the currentBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentBalance }
     *     
     */
    public void setCurrentBalance(CurrentBalance value) {
        this.currentBalance = value;
    }

    /**
     * Gets the value of the ytdRewardEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYTDRewardEarned() {
        return ytdRewardEarned;
    }

    /**
     * Sets the value of the ytdRewardEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYTDRewardEarned(BigDecimal value) {
        this.ytdRewardEarned = value;
    }

    /**
     * Gets the value of the lifeTimeRewardEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLifeTimeRewardEarned() {
        return lifeTimeRewardEarned;
    }

    /**
     * Sets the value of the lifeTimeRewardEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLifeTimeRewardEarned(BigDecimal value) {
        this.lifeTimeRewardEarned = value;
    }

}
