//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.10 at 04:54:49 PM IST 
//


package com.macys.loyalty.schemas.loyalty_transaction.ltytransactionresponse.v12_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.FaultResponse;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Offer;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.ProgramInfo;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Response;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.macys.loyalty.schemas.loyalty_transaction.ltytransactionresponse.v12_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProgramInfo_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0", "ProgramInfo");
    private final static QName _Offer_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0", "Offer");
    private final static QName _IcmRdsTransactionResp_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0", "IcmRdsTransactionResp");
    private final static QName _LtyFault_QNAME = new QName("http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0", "LtyFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.macys.loyalty.schemas.loyalty_transaction.ltytransactionresponse.v12_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Program }
     * 
     */
    public Program createProgram() {
        return new Program();
    }

    /**
     * Create an instance of {@link LtyCustServiceRewardResp }
     * 
     */
    public LtyCustServiceRewardResp createLtyCustServiceRewardResp() {
        return new LtyCustServiceRewardResp();
    }

    /**
     * Create an instance of {@link Program.RewardSummary }
     * 
     */
    public Program.RewardSummary createProgramRewardSummary() {
        return new Program.RewardSummary();
    }

    /**
     * Create an instance of {@link Award }
     * 
     */
    public Award createAward() {
        return new Award();
    }

    /**
     * Create an instance of {@link AwardAdjustment }
     * 
     */
    public AwardAdjustment createAwardAdjustment() {
        return new AwardAdjustment();
    }

    /**
     * Create an instance of {@link RewardInfo }
     * 
     */
    public RewardInfo createRewardInfo() {
        return new RewardInfo();
    }

    /**
     * Create an instance of {@link CustomerInfo }
     * 
     */
    public CustomerInfo createCustomerInfo() {
        return new CustomerInfo();
    }

    /**
     * Create an instance of {@link LtyTransactionResp }
     * 
     */
    public LtyTransactionResp createLtyTransactionResp() {
        return new LtyTransactionResp();
    }

    /**
     * Create an instance of {@link SpendInfo }
     * 
     */
    public SpendInfo createSpendInfo() {
        return new SpendInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0", name = "ProgramInfo")
    public JAXBElement<ProgramInfo> createProgramInfo(ProgramInfo value) {
        return new JAXBElement<ProgramInfo>(_ProgramInfo_QNAME, ProgramInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Offer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0", name = "Offer")
    public JAXBElement<Offer> createOffer(Offer value) {
        return new JAXBElement<Offer>(_Offer_QNAME, Offer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0", name = "IcmRdsTransactionResp")
    public JAXBElement<Response> createIcmRdsTransactionResp(Response value) {
        return new JAXBElement<Response>(_IcmRdsTransactionResp_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0", name = "LtyFault")
    public JAXBElement<FaultResponse> createLtyFault(FaultResponse value) {
        return new JAXBElement<FaultResponse>(_LtyFault_QNAME, FaultResponse.class, null, value);
    }

}
