//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.10 at 04:54:49 PM IST 
//


package com.macys.loyalty.schemas.loyalty_transaction.ltytransactionresponse.v12_0;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.ProgramInfo;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0}ProgramInfo"/>
 *         &lt;element name="RewardSummary" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}RewardGroupCode"/>
 *                   &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0}RewardInfo" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0}Award" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0}AwardAdjustment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RewardsToNextAward" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "programInfo",
    "rewardSummary",
    "award",
    "awardAdjustment",
    "rewardsToNextAward"
})
@XmlRootElement(name = "Program")
public class Program {

    @XmlElement(name = "ProgramInfo", required = true)
    protected ProgramInfo programInfo;
    @XmlElement(name = "RewardSummary")
    protected Program.RewardSummary rewardSummary;
    @XmlElement(name = "Award")
    protected List<Award> award;
    @XmlElement(name = "AwardAdjustment")
    protected List<AwardAdjustment> awardAdjustment;
    @XmlElement(name = "RewardsToNextAward")
    protected BigDecimal rewardsToNextAward;

    /**
     * Gets the value of the programInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramInfo }
     *     
     */
    public ProgramInfo getProgramInfo() {
        return programInfo;
    }

    /**
     * Sets the value of the programInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramInfo }
     *     
     */
    public void setProgramInfo(ProgramInfo value) {
        this.programInfo = value;
    }

    /**
     * Gets the value of the rewardSummary property.
     * 
     * @return
     *     possible object is
     *     {@link Program.RewardSummary }
     *     
     */
    public Program.RewardSummary getRewardSummary() {
        return rewardSummary;
    }

    /**
     * Sets the value of the rewardSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Program.RewardSummary }
     *     
     */
    public void setRewardSummary(Program.RewardSummary value) {
        this.rewardSummary = value;
    }

    /**
     * Award: Award details for the transaction Gets the value of the award property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the award property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAward().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Award }
     * 
     * 
     */
    public List<Award> getAward() {
        if (award == null) {
            award = new ArrayList<Award>();
        }
        return this.award;
    }

    /**
     * Gets the value of the awardAdjustment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the awardAdjustment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAwardAdjustment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AwardAdjustment }
     * 
     * 
     */
    public List<AwardAdjustment> getAwardAdjustment() {
        if (awardAdjustment == null) {
            awardAdjustment = new ArrayList<AwardAdjustment>();
        }
        return this.awardAdjustment;
    }

    /**
     * Gets the value of the rewardsToNextAward property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRewardsToNextAward() {
        return rewardsToNextAward;
    }

    /**
     * Sets the value of the rewardsToNextAward property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRewardsToNextAward(BigDecimal value) {
        this.rewardsToNextAward = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}RewardGroupCode"/>
     *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.transaction/LtyTransactionResponse/v12_0}RewardInfo" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rewardGroupCode",
        "rewardInfo"
    })
    public static class RewardSummary {

        @XmlElement(name = "RewardGroupCode", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
        protected String rewardGroupCode;
        @XmlElement(name = "RewardInfo")
        protected RewardInfo rewardInfo;

        /**
         * Possible Values: TFS, MYMACYS, BLM, AMEX, USL, GPGM, DINE, MMON, BMON, BINT
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRewardGroupCode() {
            return rewardGroupCode;
        }

        /**
         * Sets the value of the rewardGroupCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRewardGroupCode(String value) {
            this.rewardGroupCode = value;
        }

        /**
         * Gets the value of the rewardInfo property.
         * 
         * @return
         *     possible object is
         *     {@link RewardInfo }
         *     
         */
        public RewardInfo getRewardInfo() {
            return rewardInfo;
        }

        /**
         * Sets the value of the rewardInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link RewardInfo }
         *     
         */
        public void setRewardInfo(RewardInfo value) {
            this.rewardInfo = value;
        }

    }

}
