//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.10 at 04:54:49 PM IST 
//


package com.macys.loyalty.schemas.loyalty_transaction.ltytransactionresponse.v12_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.BeginBalance;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.Earned;
import com.macys.loyalty.schemas.loyalty_common.ltycommon.v12_0.EndBalance;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}BeginBalance"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}EndBalance"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}Earned"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}YTDRewardEarned" minOccurs="0"/>
 *         &lt;element ref="{http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0}LifeTimeRewardEarned" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "beginBalance",
    "endBalance",
    "earned",
    "ytdRewardEarned",
    "lifeTimeRewardEarned"
})
@XmlRootElement(name = "RewardInfo")
public class RewardInfo {

    @XmlElement(name = "BeginBalance", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected BeginBalance beginBalance;
    @XmlElement(name = "EndBalance", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected EndBalance endBalance;
    @XmlElement(name = "Earned", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0", required = true)
    protected Earned earned;
    @XmlElement(name = "YTDRewardEarned", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected BigDecimal ytdRewardEarned;
    @XmlElement(name = "LifeTimeRewardEarned", namespace = "http://loyalty.macys.com/schemas/loyalty.common/LtyCommon/v12_0")
    protected BigDecimal lifeTimeRewardEarned;

    /**
     * Gets the value of the beginBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BeginBalance }
     *     
     */
    public BeginBalance getBeginBalance() {
        return beginBalance;
    }

    /**
     * Sets the value of the beginBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeginBalance }
     *     
     */
    public void setBeginBalance(BeginBalance value) {
        this.beginBalance = value;
    }

    /**
     * Gets the value of the endBalance property.
     * 
     * @return
     *     possible object is
     *     {@link EndBalance }
     *     
     */
    public EndBalance getEndBalance() {
        return endBalance;
    }

    /**
     * Sets the value of the endBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndBalance }
     *     
     */
    public void setEndBalance(EndBalance value) {
        this.endBalance = value;
    }

    /**
     * Gets the value of the earned property.
     * 
     * @return
     *     possible object is
     *     {@link Earned }
     *     
     */
    public Earned getEarned() {
        return earned;
    }

    /**
     * Sets the value of the earned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Earned }
     *     
     */
    public void setEarned(Earned value) {
        this.earned = value;
    }

    /**
     * Gets the value of the ytdRewardEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYTDRewardEarned() {
        return ytdRewardEarned;
    }

    /**
     * Sets the value of the ytdRewardEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYTDRewardEarned(BigDecimal value) {
        this.ytdRewardEarned = value;
    }

    /**
     * Gets the value of the lifeTimeRewardEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLifeTimeRewardEarned() {
        return lifeTimeRewardEarned;
    }

    /**
     * Sets the value of the lifeTimeRewardEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLifeTimeRewardEarned(BigDecimal value) {
        this.lifeTimeRewardEarned = value;
    }

}
